metalos: switch-root into rw snapshot of image
Summary:
Create another template unit to switch-root into a rw snapshot per-boot instead
of just `switch-root`.

This should maybe be part of the runtime config package, which could
instantiate these units as well, but until I think about that part a bit more
this works by passing the `antlir.os-uri` kernel cmdline.

I also documented a bit of the systemd issues that I ran into, around targets
that are activated in the initrd do not get reloaded in the rootfs after the
switch-root

Reviewed By: zeroxoneb

Differential Revision: D28479014

fbshipit-source-id: e1a5c17f0da4a64c2906494e6ef7d3c645ac3227

diff --git a/antlir/vm/mount-generator b/antlir/vm/mount-generator
--- a/antlir/vm/mount-generator
+++ b/antlir/vm/mount-generator
@@ -7,27 +7,46 @@
 # files from a well-known 9p mount tag, but for now the only case where the
 # host needs to do change systemd units at runtime is for host-dependent 9pfs
 # mountpoints.
+echo "mount-generator: starting" > /dev/kmsg
 set -e
+
 normal_dir="$1"
 # allow passing EXPORTS_DIR as a pre-mounted path for unit tests
 exportsdir="$EXPORTS_DIR"
+echo "mount-generator: $1 $EXPORTS_DIR" > /dev/kmsg
 
 if [ -z "$exportsdir" ]; then
     # Usually these are already loaded, but in Antlir Linux this generator runs in
     # the initrd before systemd-modules-load.service
-    modprobe -a 9p 9pnet 9pnet_virtio
+    # Ignore any errors in modprobe and assume that the modules are already
+    # loaded, the next steps will still fail in an obvious way if 9p is not
+    # actually present.
+    echo "mount-generator: attempting to load 9p modules" > /dev/kmsg
+    modprobe -a 9p 9pnet 9pnet_virtio || true
 
     exportsdir="/run/vmtest-exports"
+    echo "mount-generator: creating $exportsdir" > /dev/kmsg
     mkdir -p "$exportsdir"
+    echo "mount-generator: mounting exports in $exportsdir" > /dev/kmsg
     mount -t 9p -oversion=9p2000.L,posixacl,cache=loose exports "$exportsdir"
+    echo "mount-generator: mounted exports in $exportsdir" > /dev/kmsg
     trap 'umount $exportsdir && rm -rf $exportsdir' EXIT
 fi
 
 mkdir -p "$normal_dir/local-fs.target.requires"
+# when running in metalos, local-fs.target will have already been activated in
+# the initrd, so we need to make it a dependency of the workload (which is sshd
+# to run the test)
+mkdir -p "$normal_dir/workload-pre.target.requires"
 
 for unit in "$exportsdir"/*.mount
 do
+    echo "mount-generator: processing $unit" > /dev/kmsg
     cp "$unit" "$normal_dir"/
     unit="$(basename "$unit")"
     ln -s "$normal_dir/$unit" "$normal_dir/local-fs.target.requires/$unit"
+    # In MetalOS vmtests, local-fs.target will be marked as completed in the
+    # initrd, so add this mount unit to workload-pre.target.requires to ensure
+    # it gets started before running the test (which is in workload.target)
+    ln -s "$normal_dir/$unit" "$normal_dir/workload-pre.target.requires/$unit"
 done
